services:
  - type: web
    name: project-2
    env: python
    plan: free
    startCommand: gunicorn --workers 1 --worker-class sync --bind 0.0.0.0:$PORT --timeout 600 --keep-alive 10 --max-requests 50 --max-requests-jitter 5 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
