services:
  - type: web
    name: project-2
    env: python
    plan: free
    startCommand: gunicorn --workers 1 --worker-class sync --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
